name: Deploy Fixbulance to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/fixbulance
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fixbulance
          sudo systemctl restart nginx
          echo "Deployment completed successfully!" 